# -*- coding: utf-8 -*-
"""Irishmain().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnL2gaci9Hsr246hBkh8TdSGOQUFYZxE
"""
import time

from helpers import with_or_without, play_audio


def get_current_time():
    current_time = time.strftime('%H:%M')
    split_time = current_time.split(':')
    return int(split_time[0]), int(split_time[1])


def get_hour_filename(hr: int, m: int):
    if m > 30:
        hr += 1
    if hr == 0:
        return 'Midnight.wav'
    else:
        if hr >= 12:
            hr = hr - 12
            return str(hr) + 'IRI.wav'
        else:
            return str(hr) + 'IRI.wav'


def get_minute_filename(m: int):
    if m == 0:
        return 'oclock.wav'
    elif m == 15 or m == 45:
        return '15IRI.wav'
    elif m > 30:
        m = 60 - m
    return str(m) + 'IRI.wav'


def ie_speak_the_clock(speed_rate=1):
    am = 2
    hour, minute = get_current_time()
    if hour >= 12:
        am = 0
    else:
        am = 1
    print("The time is " + str(hour) + ':' + str(minute))
    audio_names = ['Its.wav']
    if minute != 0:
        audio_names.append(get_minute_filename(minute))
        audio_names.append(with_or_without(minute))
        audio_names.append(get_hour_filename(hour, minute))
    else:
        audio_names.append(get_hour_filename(hour, minute))
        audio_names.append(get_minute_filename(minute))

    if hour != 0:
        if am == 1:
            audio_names.append('am.wav')
        elif am == 0:
            audio_names.append('pm.wav')
        else:
            print("Error, failed am/pm conversion")

    play_audio(audio_names, speed_rate, './IrishAudio+Logic/')
