# -*- coding: utf-8 -*-
"""Polishmain().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KdmenPckUdfKc6oOCjmdg8Pfi8rK00I8
"""
import time

from helpers import with_or_without, play_audio


def get_current_time():
    current_time = time.strftime('%H:%M')
    split_time = current_time.split(':')
    return int(split_time[0]), int(split_time[1])


def get_hour_filename(hr: int, m: int):
    if m >= 30:  # Poland has 30-60 as (x to)
        hr += 1
    if hr == 0 and m == 0:
        return 'Midnight.wav'  # midnight -polnoc
    elif hr == 0 and m > 0:
        return 'Past_Midnight.wav'  # past midnight has grammar - polnoc(y)
    else:
        if m == 0 or m > 30:
            return str(hr) + 'tha.wav'  # non possessive
        else:
            return str(hr) + 'th.wav'  # possessive


def get_minute_filename(m: int):
    if m == 0:
        pass
    elif m > 30:
        m = 60 - m
        return str(m) + 'POL.wav'
    elif m == 30:
        return 'half_to.wav'
    else:
        return str(m) + 'POL.wav'


def pl_speak_the_clock(speed_rate=1):
    hour, minute = get_current_time()
    audio_names = ['Its.wav']
    if minute != 0:
        if minute < 30:
            audio_names.append(get_minute_filename(minute))
            audio_names.append(with_or_without(minute))
        elif minute > 30:
            audio_names.append(with_or_without(minute))
            audio_names.append(get_minute_filename(minute))
        else:
            audio_names.append(get_minute_filename(minute))
    audio_names.append(get_hour_filename(hour, minute))

    play_audio(audio_names, speed_rate, './PolishAudio+Logic/')
